
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int ОТСКОБКА = 19;
  public static final int ИД = 52;
  public static final int DIVIDE = 7;
  public static final int QSTRING = 53;
  public static final int ВЫХОД = 36;
  public static final int OPENSQBRACE = 21;
  public static final int ПЛЮС = 4;
<<<<<<< HEAD
  public static final int INPUT = 37;
  public static final int CASE = 49;
=======
  public static final int РОВНЯ = 12;
  public static final int INPUT = 38;
  public static final int CASE = 50;
>>>>>>> e062649 (Fixed merge errors on my end and translated more variables)
  public static final int ОТКУДРЯВЫЙ = 17;
  public static final int ДО = 46;
  public static final int ЗАПКУДРЯВЫЙ = 18;
  public static final int FOR = 44;
  public static final int READFILE = 25;
  public static final int ПРАВДА = 34;
  public static final int LISTTYPE = 33;
  public static final int OPENFILTER = 27;
  public static final int LT = 13;
  public static final int NUMTYPE = 29;
  public static final int ЕНДЛ = 2;
  public static final int VOIDTYPE = 32;
  public static final int ПОЛОСРАСКОЛ = 23;
  public static final int UNTIL = 39;
  public static final int GEQ = 16;
<<<<<<< HEAD
  public static final int EXIT = 38;
  public static final int IF = 42;
=======
  public static final int EXIT = 39;
  public static final int ЕЩЕ = 44;
>>>>>>> e062649 (Fixed merge errors on my end and translated more variables)
  public static final int EOF = 0;
  public static final int RETURN = 47;
  public static final int error = 1;
  public static final int РАВНО = 3;
  public static final int MOD = 8;
  public static final int BREAK = 46;
  public static final int CLOSEFILTER = 28;
<<<<<<< HEAD
  public static final int ERROR = 40;
  public static final int SWITCH = 48;
=======
  public static final int ЕСЛИ = 43;
  public static final int ERROR = 41;
  public static final int SWITCH = 49;
>>>>>>> e062649 (Fixed merge errors on my end and translated more variables)
  public static final int ИЛИ = 10;
  public static final int TIMES = 6;
  public static final int МИНУС = 5;
  public static final int COLON = 24;
<<<<<<< HEAD
  public static final int ELSE = 43;
  public static final int FUNC = 41;
  public static final int WHILE = 45;
  public static final int DEFAULT = 50;
  public static final int ТЕКСТ = 30;
  public static final int ЛОГИЗНАЧ = 31;
=======
  public static final int FUNC = 42;
  public static final int DEFAULT = 51;
  public static final int ТЕКСТ = 31;
>>>>>>> e062649 (Fixed merge errors on my end and translated more variables)
  public static final int LEQ = 15;
  public static final int ЛОЖЬ = 35;
  public static final int WRITEFILE = 26;
  public static final int CLOSESQBRACE = 22;
  public static final int НЕТ = 11;
  public static final int GT = 14;
  public static final int ЦЕЛ = 51;
  public static final int И = 9;
  public static final int ЗАПСКОБКА = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ЕНДЛ",
  "РАВНО",
  "ПЛЮС",
  "МИНУС",
  "TIMES",
  "DIVIDE",
  "MOD",
  "И",
  "ИЛИ",
  "НЕТ",
  "РОВНЯ",
  "LT",
  "GT",
  "LEQ",
  "GEQ",
  "ОТКУДРЯВЫЙ",
  "ЗАПКУДРЯВЫЙ",
  "ОТСКОБКА",
  "ЗАПСКОБКА",
  "OPENSQBRACE",
  "CLOSESQBRACE",
  "ПОЛОСРАСКОЛ",
  "COLON",
  "READFILE",
  "WRITEFILE",
  "OPENFILTER",
  "CLOSEFILTER",
  "NUMTYPE",
  "ТЕКСТ",
  "ЛОГИЗНАЧ",
  "VOIDTYPE",
  "LISTTYPE",
  "ПРАВДА",
  "ЛОЖЬ",
  "ВЫХОД",
  "INPUT",
  "EXIT",
  "UNTIL",
  "ERROR",
  "FUNC",
  "ЕСЛИ",
  "ЕЩЕ",
  "FOR",
  "ДО",
  "BREAK",
  "RETURN",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "ЦЕЛ",
  "ИД",
  "QSTRING"
  };
}

