
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int ИД = 53;
  public static final int DIVIDE = 7;
  public static final int QSTRING = 54;
  public static final int OPENSQBRACE = 21;
  public static final int EQUALS = 12;
  public static final int INPUT = 38;
  public static final int CASE = 50;
  public static final int FOR = 45;
  public static final int MINUS = 5;
  public static final int CLOSEPAREN = 20;
  public static final int READFILE = 25;
  public static final int LISTTYPE = 34;
  public static final int OPENFILTER = 27;
  public static final int OPENPAREN = 19;
  public static final int LT = 13;
  public static final int NUMTYPE = 29;
  public static final int ЕНДЛ = 2;
  public static final int VOIDTYPE = 33;
  public static final int ПОЛОСРАСКОЛ = 23;
  public static final int UNTIL = 40;
  public static final int GEQ = 16;
  public static final int EXIT = 39;
  public static final int PLUS = 4;
  public static final int IF = 43;
  public static final int EOF = 0;
  public static final int RETURN = 48;
  public static final int TEXTTYPE = 30;
  public static final int TRUE = 35;
  public static final int error = 1;
  public static final int РАВНО = 3;
  public static final int MOD = 8;
  public static final int BREAK = 47;
  public static final int CLOSEFILTER = 28;
  public static final int CLOSECURLY = 18;
  public static final int ERROR = 41;
  public static final int SWITCH = 49;
  public static final int ИЛИ = 10;
  public static final int TIMES = 6;
  public static final int BOOLTYPE = 32;
  public static final int OPENCURLY = 17;
  public static final int COLON = 24;
  public static final int ELSE = 44;
  public static final int FUNC = 42;
  public static final int WHILE = 46;
  public static final int DEFAULT = 51;
  public static final int ТЕКСТ = 31;
  public static final int LEQ = 15;
  public static final int WRITEFILE = 26;
  public static final int FALSE = 36;
  public static final int CLOSESQBRACE = 22;
  public static final int НЕТ = 11;
  public static final int GT = 14;
  public static final int ЦЕЛ = 52;
  public static final int выход = 37;
  public static final int И = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ЕНДЛ",
  "РАВНО",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MOD",
  "И",
  "ИЛИ",
  "НЕТ",
  "EQUALS",
  "LT",
  "GT",
  "LEQ",
  "GEQ",
  "OPENCURLY",
  "CLOSECURLY",
  "OPENPAREN",
  "CLOSEPAREN",
  "OPENSQBRACE",
  "CLOSESQBRACE",
  "ПОЛОСРАСКОЛ",
  "COLON",
  "READFILE",
  "WRITEFILE",
  "OPENFILTER",
  "CLOSEFILTER",
  "NUMTYPE",
  "TEXTTYPE",
  "ТЕКСТ",
  "BOOLTYPE",
  "VOIDTYPE",
  "LISTTYPE",
  "TRUE",
  "FALSE",
  "выход",
  "INPUT",
  "EXIT",
  "UNTIL",
  "ERROR",
  "FUNC",
  "IF",
  "ELSE",
  "FOR",
  "WHILE",
  "BREAK",
  "RETURN",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "ЦЕЛ",
  "ИД",
  "QSTRING"
  };
}

