/* The following code was generated by JFlex 1.7.0 */

// Symbol
import java_cup.runtime.*;

/**
 * This class is the lexer (i.e., scanner) for the Streamer
 * language (that students complete in CSCI 340).
 */

class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\5\1\4\1\105\1\106\1\3\22\0\1\5\1\65\1\103"+
    "\2\0\1\62\1\63\1\0\1\72\1\73\1\60\1\56\1\102\1\57"+
    "\1\101\1\61\12\1\1\77\1\76\1\66\1\55\1\67\1\100\1\0"+
    "\32\2\1\74\1\104\1\75\3\0\1\32\1\51\1\53\1\54\1\30"+
    "\1\31\1\2\1\50\1\41\1\2\1\52\1\33\1\10\1\6\1\46"+
    "\1\42\1\2\1\27\1\34\1\26\1\7\1\2\1\47\3\2\1\70"+
    "\1\64\1\71\7\0\1\105\u038a\0\40\2\1\23\1\44\1\35\1\17"+
    "\1\40\1\12\1\2\1\21\1\20\1\2\1\13\1\15\1\2\1\22"+
    "\1\16\1\25\1\2\1\14\1\11\1\2\1\45\1\37\1\2\1\24"+
    "\1\43\2\2\1\36\4\2\u1bd8\0\1\105\1\105\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\2\4\23\3\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\2\1\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\1\1\26\1\1\1\0\20\3\1\27\5\3\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\0\1\41\1\0\1\2\1\42\13\3\1\43\17\3"+
    "\1\44\1\3\1\45\4\3\1\46\2\3\1\47\1\3"+
    "\1\50\1\51\4\3\1\52\1\3\1\53\1\3\1\54"+
    "\1\55\1\56\1\57\1\3\1\60\1\3\1\61\1\62"+
    "\1\63\1\64\2\3\1\65\1\66";

  private static int [] zzUnpackAction() {
    int [] result = new int[148];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\107\0\216\0\325\0\u011c\0\107\0\u0163\0\u01aa"+
    "\0\u01f1\0\u0238\0\u027f\0\u02c6\0\u030d\0\u0354\0\u039b\0\u03e2"+
    "\0\u0429\0\u0470\0\u04b7\0\u04fe\0\u0545\0\u058c\0\u05d3\0\u061a"+
    "\0\u0661\0\u06a8\0\107\0\107\0\107\0\107\0\107\0\u06ef"+
    "\0\u0736\0\107\0\u077d\0\u07c4\0\107\0\107\0\107\0\107"+
    "\0\u080b\0\107\0\107\0\107\0\u0852\0\107\0\u0899\0\u08e0"+
    "\0\u0927\0\u096e\0\u09b5\0\u09fc\0\u0a43\0\u0a8a\0\u0ad1\0\u0b18"+
    "\0\u0b5f\0\u0ba6\0\u0bed\0\u0c34\0\u0c7b\0\u0cc2\0\u0d09\0\u0d50"+
    "\0\325\0\u0d97\0\u0dde\0\u0e25\0\u0e6c\0\u0eb3\0\107\0\107"+
    "\0\107\0\107\0\107\0\107\0\107\0\107\0\107\0\u0899"+
    "\0\107\0\u0efa\0\u08e0\0\325\0\u0f41\0\u0f88\0\u0fcf\0\u1016"+
    "\0\u105d\0\u10a4\0\u10eb\0\u1132\0\u1179\0\u11c0\0\u1207\0\325"+
    "\0\u124e\0\u1295\0\u12dc\0\u1323\0\u136a\0\u13b1\0\u13f8\0\u143f"+
    "\0\u1486\0\u14cd\0\u1514\0\u155b\0\u15a2\0\u15e9\0\u1630\0\325"+
    "\0\u1677\0\325\0\u16be\0\u1705\0\u174c\0\u1793\0\325\0\u17da"+
    "\0\u1821\0\325\0\u1868\0\325\0\325\0\u18af\0\u18f6\0\u193d"+
    "\0\u1984\0\325\0\u19cb\0\325\0\u1a12\0\325\0\325\0\325"+
    "\0\325\0\u1a59\0\325\0\u1aa0\0\325\0\325\0\325\0\325"+
    "\0\u1ae7\0\u1b2e\0\325\0\325";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[148];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\2\6\1\7\1\10\1\4"+
    "\1\11\2\4\1\12\1\13\1\14\3\4\1\15\3\4"+
    "\1\16\1\17\1\20\1\21\2\4\1\22\1\23\3\4"+
    "\1\24\3\4\1\25\1\4\1\26\1\4\1\27\1\4"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\50\1\51\1\52\1\53\1\54\1\55\1\56\1\2"+
    "\1\57\1\2\1\0\1\6\110\0\1\3\100\0\1\60"+
    "\5\0\2\4\3\0\47\4\36\0\1\6\103\0\2\4"+
    "\3\0\1\4\1\61\45\4\33\0\2\4\3\0\1\62"+
    "\46\4\33\0\2\4\3\0\4\4\1\63\42\4\33\0"+
    "\2\4\3\0\17\4\1\64\27\4\33\0\2\4\3\0"+
    "\10\4\1\65\36\4\33\0\2\4\3\0\35\4\1\66"+
    "\11\4\33\0\2\4\3\0\12\4\1\67\2\4\1\70"+
    "\31\4\33\0\2\4\3\0\21\4\1\71\25\4\33\0"+
    "\2\4\3\0\22\4\1\72\24\4\33\0\2\4\3\0"+
    "\25\4\1\73\21\4\33\0\2\4\3\0\24\4\1\74"+
    "\13\4\1\75\6\4\33\0\2\4\3\0\41\4\1\76"+
    "\5\4\33\0\2\4\3\0\30\4\1\77\16\4\33\0"+
    "\2\4\3\0\1\100\22\4\1\101\23\4\33\0\2\4"+
    "\3\0\15\4\1\102\31\4\33\0\2\4\3\0\42\4"+
    "\1\103\4\4\33\0\2\4\3\0\21\4\1\104\25\4"+
    "\33\0\2\4\3\0\24\4\1\105\22\4\33\0\2\4"+
    "\3\0\22\4\1\106\24\4\107\0\1\107\114\0\1\110"+
    "\107\0\1\111\77\0\1\112\10\0\1\113\75\0\1\114"+
    "\11\0\1\115\117\0\1\116\103\0\1\117\11\0\103\120"+
    "\1\121\1\122\2\120\1\0\1\123\106\0\2\4\3\0"+
    "\2\4\1\124\44\4\33\0\2\4\3\0\20\4\1\125"+
    "\26\4\33\0\2\4\3\0\5\4\1\126\41\4\33\0"+
    "\2\4\3\0\12\4\1\127\34\4\33\0\2\4\3\0"+
    "\11\4\1\130\35\4\33\0\2\4\3\0\12\4\1\131"+
    "\34\4\33\0\2\4\3\0\16\4\1\132\30\4\33\0"+
    "\2\4\3\0\13\4\1\133\33\4\33\0\2\4\3\0"+
    "\1\4\1\134\45\4\33\0\2\4\3\0\20\4\1\135"+
    "\26\4\33\0\2\4\3\0\26\4\1\136\20\4\33\0"+
    "\2\4\3\0\25\4\1\137\21\4\33\0\2\4\3\0"+
    "\21\4\1\140\25\4\33\0\2\4\3\0\33\4\1\141"+
    "\13\4\33\0\2\4\3\0\31\4\1\142\15\4\33\0"+
    "\2\4\3\0\34\4\1\143\12\4\33\0\2\4\3\0"+
    "\14\4\1\144\32\4\33\0\2\4\3\0\33\4\1\145"+
    "\13\4\33\0\2\4\3\0\22\4\1\146\24\4\33\0"+
    "\2\4\3\0\26\4\1\147\20\4\33\0\2\4\3\0"+
    "\23\4\1\150\23\4\32\0\3\120\2\0\100\120\3\0"+
    "\2\4\3\0\33\4\1\151\13\4\33\0\2\4\3\0"+
    "\6\4\1\152\40\4\33\0\2\4\3\0\6\4\1\153"+
    "\40\4\33\0\2\4\3\0\12\4\1\154\34\4\33\0"+
    "\2\4\3\0\36\4\1\155\10\4\33\0\2\4\3\0"+
    "\4\4\1\156\42\4\33\0\2\4\3\0\15\4\1\157"+
    "\31\4\33\0\2\4\3\0\22\4\1\160\24\4\33\0"+
    "\2\4\3\0\1\4\1\161\45\4\33\0\2\4\3\0"+
    "\22\4\1\162\24\4\33\0\2\4\3\0\26\4\1\163"+
    "\20\4\33\0\2\4\3\0\20\4\1\164\26\4\33\0"+
    "\2\4\3\0\10\4\1\165\36\4\33\0\2\4\3\0"+
    "\1\4\1\166\45\4\33\0\2\4\3\0\5\4\1\167"+
    "\41\4\33\0\2\4\3\0\25\4\1\170\21\4\33\0"+
    "\2\4\3\0\24\4\1\171\22\4\33\0\2\4\3\0"+
    "\22\4\1\172\24\4\33\0\2\4\3\0\24\4\1\173"+
    "\22\4\33\0\2\4\3\0\25\4\1\174\21\4\33\0"+
    "\2\4\3\0\3\4\1\175\43\4\33\0\2\4\3\0"+
    "\10\4\1\176\36\4\33\0\2\4\3\0\13\4\1\177"+
    "\33\4\33\0\2\4\3\0\5\4\1\200\41\4\33\0"+
    "\2\4\3\0\11\4\1\201\35\4\33\0\2\4\3\0"+
    "\32\4\1\202\14\4\33\0\2\4\3\0\21\4\1\203"+
    "\25\4\33\0\2\4\3\0\22\4\1\204\24\4\33\0"+
    "\2\4\3\0\45\4\1\205\1\4\33\0\2\4\3\0"+
    "\32\4\1\206\14\4\33\0\2\4\3\0\20\4\1\207"+
    "\26\4\33\0\2\4\3\0\22\4\1\210\24\4\33\0"+
    "\2\4\3\0\44\4\1\211\2\4\33\0\2\4\3\0"+
    "\1\4\1\212\45\4\33\0\2\4\3\0\5\4\1\213"+
    "\41\4\33\0\2\4\3\0\14\4\1\214\32\4\33\0"+
    "\2\4\3\0\15\4\1\215\31\4\33\0\2\4\3\0"+
    "\10\4\1\216\36\4\33\0\2\4\3\0\1\217\46\4"+
    "\33\0\2\4\3\0\42\4\1\220\4\4\33\0\2\4"+
    "\3\0\25\4\1\221\21\4\33\0\2\4\3\0\15\4"+
    "\1\222\31\4\33\0\2\4\3\0\20\4\1\223\26\4"+
    "\33\0\2\4\3\0\16\4\1\224\30\4\32\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7029];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\24\1\5\11\2\1\1\11"+
    "\2\1\4\11\1\1\3\11\1\1\1\11\1\1\1\0"+
    "\26\1\11\11\1\0\1\11\1\0\102\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[148];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
/**
 * Make symbol of the given type, with a String value.
 */
private Symbol makeSym(int type, String value) {
    return new Symbol(type, yyline+1, yycolumn+1, value);
}

/**
 * Make a symbol of the given type, with no value.
 */
private Symbol makeSym(int type) {
    return new Symbol(type, yyline+1, yycolumn+1);
}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 228) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new Error("Illegal character <" + yytext() + "> at line " +
                        (yyline+1) + " column " + (yycolumn+1));
            } 
            // fall through
          case 55: break;
          case 2: 
            { return makeSym(sym.ЦЕЛ, yytext());
            } 
            // fall through
          case 56: break;
          case 3: 
            { return makeSym(sym.ИД, yytext());
            } 
            // fall through
          case 57: break;
          case 4: 
            { ;
            } 
            // fall through
          case 58: break;
          case 5: 
            { return makeSym(sym.РАВНО);
            } 
            // fall through
          case 59: break;
          case 6: 
            { return makeSym(sym.ПЛЮС);
            } 
            // fall through
          case 60: break;
          case 7: 
            { return makeSym(sym.МИНУС);
            } 
            // fall through
          case 61: break;
          case 8: 
            { return makeSym(sym.TIMES);
            } 
            // fall through
          case 62: break;
          case 9: 
            { return makeSym(sym.DIVIDE);
            } 
            // fall through
          case 63: break;
          case 10: 
            { return makeSym(sym.MOD);
            } 
            // fall through
          case 64: break;
          case 11: 
            { return makeSym(sym.НЕТ);
            } 
            // fall through
          case 65: break;
          case 12: 
            { return makeSym(sym.LT);
            } 
            // fall through
          case 66: break;
          case 13: 
            { return makeSym(sym.GT);
            } 
            // fall through
          case 67: break;
          case 14: 
            { return makeSym(sym.ОТКУДРЯВЫЙ);
            } 
            // fall through
          case 68: break;
          case 15: 
            { return makeSym(sym.ЗАПКУДРЯВЫЙ);
            } 
            // fall through
          case 69: break;
          case 16: 
            { return makeSym(sym.ОТСКОБКА);
            } 
            // fall through
          case 70: break;
          case 17: 
            { return makeSym(sym.ЗАПСКОБКА);
            } 
            // fall through
          case 71: break;
          case 18: 
            { return makeSym(sym.OPENSQBRACE);
            } 
            // fall through
          case 72: break;
          case 19: 
            { return makeSym(sym.CLOSESQBRACE);
            } 
            // fall through
          case 73: break;
          case 20: 
            { return makeSym(sym.ПОЛОСРАСКОЛ);
            } 
            // fall through
          case 74: break;
          case 21: 
            { return makeSym(sym.COLON);
            } 
            // fall through
          case 75: break;
          case 22: 
            { return makeSym(sym.ЕНДЛ);
            } 
            // fall through
          case 76: break;
          case 23: 
            { return makeSym(sym.ЕСЛИ);
            } 
            // fall through
          case 77: break;
          case 24: 
            { return makeSym(sym.РОВНЯ);
            } 
            // fall through
          case 78: break;
          case 25: 
            { return makeSym(sym.И);
            } 
            // fall through
          case 79: break;
          case 26: 
            { return makeSym(sym.ИЛИ);
            } 
            // fall through
          case 80: break;
          case 27: 
            { return makeSym(sym.LEQ);
            } 
            // fall through
          case 81: break;
          case 28: 
            { return makeSym(sym.READFILE);
            } 
            // fall through
          case 82: break;
          case 29: 
            { return makeSym(sym.GEQ);
            } 
            // fall through
          case 83: break;
          case 30: 
            { return makeSym(sym.WRITEFILE);
            } 
            // fall through
          case 84: break;
          case 31: 
            { return makeSym(sym.OPENFILTER);
            } 
            // fall through
          case 85: break;
          case 32: 
            { return makeSym(sym.CLOSEFILTER);
            } 
            // fall through
          case 86: break;
          case 33: 
            { return makeSym(sym.QSTRING, yytext());
            } 
            // fall through
          case 87: break;
          case 34: 
            { return makeSym(sym.NUMTYPE);
            } 
            // fall through
          case 88: break;
          case 35: 
            { return makeSym(sym.FOR);
            } 
            // fall through
          case 89: break;
          case 36: 
            { return makeSym(sym.ПРАВДА);
            } 
            // fall through
          case 90: break;
          case 37: 
            { return makeSym(sym.ЕЩЕ);
            } 
            // fall through
          case 91: break;
          case 38: 
            { return makeSym(sym.ФАНК);
            } 
            // fall through
          case 92: break;
          case 39: 
            { return makeSym(sym.CASE);
            } 
            // fall through
          case 93: break;
          case 40: 
            { return makeSym(sym.UNTIL);
            } 
            // fall through
          case 94: break;
          case 41: 
            { return makeSym(sym.ТЕКСТ);
            } 
            // fall through
          case 95: break;
          case 42: 
            { return makeSym(sym.НАЗАД);
            } 
            // fall through
          case 96: break;
          case 43: 
            { return makeSym(sym.ЛОЖЬ);
            } 
            // fall through
          case 97: break;
          case 44: 
            { return makeSym(sym.ВЫХОД);
            } 
            // fall through
          case 98: break;
          case 45: 
            { return makeSym(sym.INPUT);
            } 
            // fall through
          case 99: break;
          case 46: 
            { return makeSym(sym.ДО);
            } 
            // fall through
          case 100: break;
          case 47: 
            { return makeSym(sym.BREAK);
            } 
            // fall through
          case 101: break;
          case 48: 
            { return makeSym(sym.СПИСОК);
            } 
            // fall through
          case 102: break;
          case 49: 
            { return makeSym(sym.ОШИБКА);
            } 
            // fall through
          case 103: break;
          case 50: 
            { return makeSym(sym.НИЧЕГО);
            } 
            // fall through
          case 104: break;
          case 51: 
            { return makeSym(sym.RETURN);
            } 
            // fall through
          case 105: break;
          case 52: 
            { return makeSym(sym.SWITCH);
            } 
            // fall through
          case 106: break;
          case 53: 
            { return makeSym(sym.DEFAULT);
            } 
            // fall through
          case 107: break;
          case 54: 
            { return makeSym(sym.ЛОГИЗНАЧ);
            } 
            // fall through
          case 108: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
